### ISSUE TITLE
Helm throws error

### ISSUE THREAD

**Issue by ajinabraham** [deep-security/smartcheck-helm#14]
ENVIRONMENT
```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.2"}
```
```
$eksctl create cluster
$ helm install --set auth.masterPassword=xxx \
>   deepsecurity-smartcheck \
>   https://github.com/deep-security/smartcheck-helm/archive/master.tar.gz
Error: chart illegally contains content outside the base directory: "pax_global_header"
```
This is fixed by extracting the tar package and from within the root directory
```
helm install \
>   --set auth.masterPassword=xxxx \
>   deepsecurity-smartcheck . 
```

Would be nice to fix this or update the readme.

**Comment by robmaynardjr** [comment]
Instead of auth.masterPassword, the latest version has this item as auth.secretSeed. Have you tried with that in the helm command ?

`## activationCode is the product activation code.
##
## Default value: (none)
activationCode: YOUR-CODE-HERE

auth:
  ## secretSeed is used as part of the password generation process for
  ## all auto-generated internal passwords, ensuring that each installation of
  ## Deep Security Smart Check has different passwords.
  ##
  ## Default value: {must be provided by the installer}
  secretSeed: YOUR-SECRET-HERE`

**Comment by glb** [comment]
@ajinabraham the error message you are seeing is due to [a bug in Helm 3.0.0](https://github.com/helm/helm/pull/7085); [we recommend using Helm 3.0.1 or later](https://github.com/deep-security/smartcheck-helm#helm-3).

Thanks for trying out Deep Security Smart Check!
