### ISSUE TITLE
metrics  CrashLoopBackOff  with error  --license-url

### ISSUE THREAD

**Issue by sinycn** [deep-security/smartcheck-helm#17]
Hi 
when i deploy smartcheck in aws eks, it shows:
metrics-5bdbb7994-j22k6              0/1     CrashLoopBackOff   1148       4d1h
when i check logs  kubectl logs  metrics-5bdbb7994-j22k6 -n deep-security
Error: unknown flag: --license-url
but i do not modify any configuration of license-url

**Comment by glb** [comment]
Hi @sinycn ! Thanks for reporting this issue, we'll take a look and get back to you!

**Comment by glb** [comment]
Hi @sinycn ! This appears to happen only when the `run` parameter is missing from the container's `args` list. Have you modified the chart contents?

**Comment by glb** [comment]
Thanks @sinycn for reaching out through Trend support channels; for other folks who may come across this issue, it turned out to be an issue with the way that Deep Security Smart Check was installed.

It is a good practice to use the `overrides.yaml` mechanism described in the README to collect any custom settings when installing.
