### ISSUE TITLE
unable to start smart check

### ISSUE THREAD

**Issue by sinycn** [deep-security/smartcheck-helm#9]
when i install smart check  in k8s it start failed 
[root@lothar-k8s01 tmp]# kubectl get pod
NAME                                 READY   STATUS             RESTARTS   AGE
auth-6fc794d6f9-czflv                0/1     CrashLoopBackOff   23         72m
content-scan-5b45f4587f-fs8qn        1/1     Running            0          72m
db-6c9dcdc7d-xk6nn                   0/1     Pending            0          72m
docs-6cc4797f7b-7pdfn                1/1     Running            0          72m
frontend-68984d9c8d-dk28m            1/1     Running            0          72m
license-6b9b946b98-g79bg             1/1     Running            0          72m
malware-scan-7657b87695-h784c        1/1     Running            18         72m
metrics-collector-1560841200-gpddm   0/1     Pending            0          11m
openscap-scan-57ddb5c4d6-pjtsx       0/2     CrashLoopBackOff   40         72m
proxy-579964db6d-bhmmt               0/1     CrashLoopBackOff   18         72m
registryviews-7cc5d997d4-6769t       0/1     CrashLoopBackOff   23         72m
scan-c896b854f-c2pq4                 0/1     CrashLoopBackOff   23         72m
vulnerability-db-7499979c5d-xrpvp    0/1     Pending            0          72m
vulnerability-scan-79dc795c7-hx8bv   0/1     CrashLoopBackOff   15         72m

do you have any idea about troubleshooting?

**Comment by ggrover** [comment]
Could you run the following command and provide the output?
`kubectl describe pods auth-6fc794d6f9-czflv`

**Comment by glb** [comment]
Hi @sinycn! Sorry to see that you're having trouble getting started. I see that the `db` and `vulnerability-db` pods are in `Pending` state; this typically happens when they are waiting for their persistent volumes to be mounted. The other pods that are having problems are all dependent on the database pods, and this is why they're failing to start up.

At the moment Deep Security Smart Check requires persistent volumes for the databases; we hope to release support for using an offboard database soon so that you can run without persistent volumes. 

Once you get persistent volumes working in your cluster, you should be good to go!
